services:
  - type: web
    name: workout-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: workout-tracker-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-netlify-app.netlify.app

databases:
  - name: workout-tracker-db
    databaseName: workout_tracker
    user: workout_tracker_user
    plan: free