services:
  - type: web
    name: workout-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard as environment variable
      - key: FRONTEND_URL
        sync: false # Set this in Render dashboard as environment variable